### ISSUE TITLE
window: Small resolution on first run.

### ISSUE THREAD

**Issue by ghost** [Monika-After-Story/DDLCModTemplate#1]
(Writing this in response to what Pi said. A documentation of the issue I guess.)

One of the (small, no pun intended) issues with the mod template is the small resolution it runs on when first running the game. While not a _breaking_ issue, it's still something to note for future individuals who use this template.

**Comment by therationalpi** [comment]
Thanks for opening the issue on this

**Comment by ghost** [comment]
Update: Window resolution is set in gui.rpy. 

init python:
    gui.init(1280, 720)
    #config.gl_resize = False

Found by haloff1 in the MonikaModDev server.

**Comment by therationalpi** [comment]
I figured this out. My screen resolution is just really high.
