### ISSUE TITLE
Unable to start game with mod due to rpyc error

### ISSUE THREAD

**Issue by eonisbuffering** [Monika-After-Story/DDLCModTemplate#17]
After multiple attempts to start up the mod I made with the rpyc, it couldn't run. The thing is, it only runs with the rpy file and only after it compiles the game in that directory the game starts. Can someone help me?

`I'm sorry, but an uncaught exception occurred.

While running game code:
Exception: Could not load file C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club/game/script.rpyc.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club\renpy\script.py", line 745, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn)
Exception: Could not load file C:\Program Files (x86)\Steam\SteamApps\common\Doki Doki Literature Club/game/script.rpyc.`

**Comment by therationalpi** [comment]
I'm sure you've already moved on from this, but the most likely cause is that you are using an incompatible version of the Renpy SDK. Please click on "About" in your Renpy program and ensure that it displays the same version as this:

<img width="912" alt="screen shot 2017-12-05 at 9 41 19 pm" src="https://user-images.githubusercontent.com/8276005/33641815-13b5141e-da05-11e7-90ab-3bc6d8fbd79f.png">

If it shows 6.99.13 or anything else, please go download the correct version from[ here](https://www.renpy.org/release/6.99.12). This should fix your problem.
