### ISSUE TITLE
Issue with module singleton??

### ISSUE THREAD

**Issue by heygo67** [Monika-After-Story/DDLCModTemplate#19]
Whenever I try to execute renpy.exe, it always pops up with a notepad saying that there was an error. Here's a picture of it.
![singleton_module](https://user-images.githubusercontent.com/34780401/34324054-2bed5f6a-e828-11e7-89cf-e980ae47c317.png)

**Comment by BloodlessVenus** [comment]
there is a file in the doki doki game files that is called singleton.py
I don't remember how to get to it but try looking around
