### ISSUE TITLE
Tutorial trouble - where is call prologue from _call_prologue?

### ISSUE THREAD

**Issue by Onion-Bubs** [Monika-After-Story/DDLCModTemplate#23]
So I've got to the point in the tutorial where I need to find the line "call prologue from _call_prologue" in script.rpy but I have checked script.rpy multiple times and that line does not exist.

The tutorial also said just before that that I needed to delete tutorial.rpy but the closest filename I could find was tutorials.rpy (note the plural), which makes me wonder if the tutorial is in fact outdated. If that's the case, then what is it that I need to do?

**Comment by therationalpi** [comment]
The tutorial is not outdated, but there were a few errors that got through testing. I'm going to go back and make some changes to improve the experience on this.
