### ISSUE TITLE
Using the template README.md

### ISSUE THREAD

**Issue by therationalpi** [Monika-After-Story/DDLCModTemplate#3]
Need a README.md for the repository, and for reference for first time users of the template.

It should explain the features of the template, and how to get started building a mod.

Short version:

Download Renpy SDK, Fork this git into a folder in Renpy's working directory. Drop the .rpa files from DDLC into the /game directory. Launch the project in Renpy, and it should compile and run. Click Build Distributions in Renpy and select "DDLC Compatible Mod" This will make a cross-platform zip file with the files for the mod and installation instructions.

**Comment by ghost** [comment]
Pull Request has been made to make the README much cleaner & list template features.

**Comment by therationalpi** [comment]
Big improvement! I'll give it a second pass and we should be good.

**Comment by therationalpi** [comment]
Alright, second pass done. I think it's viable now.
