### ISSUE TITLE
Monika's tutorial: How to make a mod

### ISSUE THREAD

**Issue by spidey32** [Monika-After-Story/DDLCModTemplate#35]
At least the first Monika tutorial does not work.
After copying the original DDLC directory to the renpy directory, Monika asks to change the name of the original DDLC directory to "Monika DDLC route".

Then we try to start it from the Reply program and it does not work.
I've tried with the initial version 0.1.0, and it does start.

Then she asks us to delete the file "tutorial.rpy" (there are the files "tutorials.rpy" and "tutorials.rpyc"). Then, the passage of the script becomes even more complicated. What script.rpy file? "The line that Monika mentions (" call prologue from _call_prologue ") does not appear, but a line like this:
     if persistent.example_seen:
         call tutorial_selection
     else:
         call example_chapter from _call_example_chapter

Please, update tutorial of Monika ...

**Comment by ThePotatoGuy** [comment]
fixed in latest version of mod template
